### ISSUE TITLE
CSS Selectors field

### ISSUE THREAD

**Issue by ADDISON74** [fballiano/openmage-cloudflare-turnstile#1]
I just installed the extension. How the classes/id's appear creates confusion. That space at the beginning of the line is extra.

![formating](https://github.com/fballiano/openmage-cloudflare-turnstile/assets/8360474/76cec378-7807-4eef-a841-4f005bf77f1c)

Is this what it should look like?

![formating_2](https://github.com/fballiano/openmage-cloudflare-turnstile/assets/8360474/d1f0bd75-d4fa-46fc-b2ac-27e4d161aeac)

**Comment by fballiano** [comment]
probably phpstorm decided to do some magic and reformatted the file

should be solved in 0.2.0:
https://github.com/fballiano/openmage-cloudflare-turnstile/releases/tag/0.2.0

thanks!

**Comment by ADDISON74** [comment]
You are welcome.
