### ISSUE TITLE
Some ideas

### ISSUE THREAD

**Issue by ADDISON74** [fballiano/openmage-cloudflare-turnstile#2]
1 - I would mention in the README file the steps for disabling the extension when, for example, on the login form in the Backend, Cloudflare Turnstile has a temporary technical issue and it is blocking the access. Disable the extension in the database and clear the cache.

2 - Disabling on a form identified by CSS selectors is done by deleting the responsible line from the Backend. I would go a little further and introduce a new feature. If a line is preceded by // then that line will be skipped.

3 - The extension needs translations.

**Question**: what happens if, for better visibility, I insert empty lines between the existing ones? I have not checked whether or not they are taken into account.

**Comment by fballiano** [comment]
1. done

**Comment by fballiano** [comment]
I think I've done everything in https://github.com/fballiano/openmage-cloudflare-turnstile/releases/tag/0.3.0 ;-)
